### ISSUE TITLE
Something something ids and keys

### ISSUE THREAD

**Issue by heinburger** [murrayju/durak#4]
`Warning: Encountered two children with the same key, 'X:X'` - so this is flooding the console as I'm sure you are aware - the `ids` for the cards are not unique which makes this interesting

I'm just wondering what you thought process was here - I feel like if you build a deck, all the cards should be assigned a unique key and another attribute should control their state (flipped or not) - It seems like we are controlling both of these things with the id field. I think it is important to not show the card identity in the page's inspectable elements, so your approach makes sense, but there should be some kind of uuid, right?

**Comment by murrayju** [comment]
Yeah, so when I designed the data format, I was focused on hiding secret data from the user, and minimizing the data over the wire. We certainly _could_ add a uuid to each card, but that feels like overkill just to fix some React warning...

The key is of course useful for rendering the hand with visible cards efficiently, but for the upside down hands it wouldn't optimize anything anyways. Since we're sharing the same component for this, I'll just use the array index when the card is face down (and the real id when face up).
